[build]
  publish = "."

# Single Page App fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security and sensible defaults
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
